### ISSUE TITLE
JSONXX Error

### ISSUE THREAD

**Issue by bossotron13** [guided-hacking/GH-Offset-Dumper#3]
Im not sure what to put, compiled in all different settings (Debug Release x64 x86) same error

![image](https://user-images.githubusercontent.com/51792884/75211116-010fc680-5751-11ea-99d3-f9d5bd0a314d.png)

**Comment by GH-Rake** [comment]
you need to put config.json in the same folder as the exe

**Comment by bossotron13** [comment]
![image](https://user-images.githubusercontent.com/51792884/75211940-69f83e00-5753-11ea-91c1-52806b0adaf7.png)

still same error, unless you mean a different one. i just made the config.json

**Comment by bossotron13** [comment]
I got it, thank you. maybe add a readme and put that in there from the actual repo. if it already in there just ignore this.

**Comment by GH-Rake** [comment]
"Put an updated config.json in the same folder as GH-Offset-Dumper.exe"

**Comment by bossotron13** [comment]
yep i just checked im dumb
